config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :categories, only: [:index, :show, :new, :create] do
      resources :spendings, only: [:index, :show, :new, :create]
    end
  end

  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is? :admin
      can :manage, :all
    else
      can :read, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :spendings

  validates :name, length: { in: 1..50 }, presence: true, allow_blank: false
  validates :icon, presence: true, allow_blank: false
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, length: { in: 1..50 }, presence: true, allow_blank: false
  validates :amount, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }

  has_many :categories
  has_many :payments

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
    @spendings = Spending.all
    @total = 0
  end

  def show
    @category = Category.find(params[:id])
    @spendings = Spending.all
    @spending = Spending.new
    @total = 0
  end

  def new
    @user = current_user
    @category = @user.categories.new
    @category_icons = [
      ['Housing', ActionController::Base.helpers.image_path('Housing.png')],
      ['Transportation', ActionController::Base.helpers.image_path('Transportation.png')],
      ['Food', ActionController::Base.helpers.image_path('Food.png')],
      ['Utilities', ActionController::Base.helpers.image_path('Utilities.png')],
      ['Clothing', ActionController::Base.helpers.image_path('Clothing.png')],
      ['Medical', ActionController::Base.helpers.image_path('Medical.png')],
      ['Insurance', ActionController::Base.helpers.image_path('Insurance.png')],
      ['Supplies', ActionController::Base.helpers.image_path('Supplies.png')],
      ['Personal', ActionController::Base.helpers.image_path('Personal.png')],
      ['Education', ActionController::Base.helpers.image_path('Education.png')],
      ['Entertainment', ActionController::Base.helpers.image_path('Entertainment.png')],
      ['Business', ActionController::Base.helpers.image_path('Business.png')],
      ['Repairs', ActionController::Base.helpers.image_path('Repairs.png')]
    ]
  end

  def create
    @user = current_user
    @category = @user.categories.new(category_params)

    if @category.save
      flash[:notice] = 'The category have been created successfully.'
      redirect_to "/users/#{current_user.id}/categories"
    else
      flash[:alert] = 'Adding a new category failed.'
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:user_id, :name, :icon)
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  def index
    @spendings = Spending.all
  end

  def show
    @spending = Spending.new
  end

  def new
    @spending = Spending.new
    @categories = current_user.categories
  end

  def create
    @spending = Spending.new(spending_params)

    respond_to do |format|
      if @spending.save
        format.html { redirect_to user_categories_path, notice: 'The spending was successfully recorded.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def spending_params
    params.require(:spending).permit(:user_id, :name, :amount, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return redirect_to "/users/#{current_user.id}/categories" if current_user
  end

  def new
    @user = User.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_total.html.erb
<% @spendings.each do |spending| %>
  <% if (spending.category_id == @category.id) then %>
    <% @total = @total + spending.amount %>
  <% end %>
<% end %>

app/views/categories/index.html.erb
<div class="container-full">
  <div class="header-block">
    <i class="fa-solid fa-bars"></i>
    <span class='title'>Categories</span>
    <i class="fa-solid fa-magnifying-glass"></i>
  </div>
</div>
<div class='welcome'>
  <span class='great'>Welcome, <%= current_user.name %></span>
  <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: 'logout' %>
</div>
<div class="categories-list">
  <ul class="list-group">
    <% @categories.each do |category| %>
    <li class="cat-card">
      <div class="cat-details">
        <div class="left">
          <div>
            <p class="cat-icon"><%= image_tag category.icon %></p>
          </div>
          <div>
            <%= link_to "/users/#{current_user.id}/categories/#{category.id}", class: "cat-link" do %>
              <h5 class="cat-name"><%= category.name%></h5>
            <% end %>
          </div>
        </div>
        <div>
          <% @spendings.each do |spending| %>
          <% if (spending.category_id == category.id) then %>
            <% @total = @total + spending.amount %>
            <% end %>
          <% end %>
          <span class="total amount">Total: $<%= @total %>0</span>
          <% @total = 0 %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>
<div class="cat-div">
  <div class="actions-inner">
    <%= link_to 'ADD NEW CATEGORY', new_user_category_path, class: 'cat-new-btn' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container-full">
  <div class="header-block">
    <%= link_to ('<i class="fa-solid fa-arrow-left"></i>').html_safe, root_path, { 'class': 'arrow'} %>
    <span class="main-title">Add new category</span>
    <i class="fa-solid fa-magnifying-glass"></i>
  </div>
  <div class="categories-list">
    <%= form_with model: @category, url: "/users/#{current_user.id}/categories", method: :post do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="field select">
        <%= form.select :icon, [["Category's icon", ''],
                                ['Housing', 'Housing.png'], ['Transportation', 'Transportation.png'], ['Food', 'Food.png'],
                                ['Utilities', 'Utilities.png'], ['Clothing', 'Clothing.png'], ['Medical', 'Medical.png'],
                                ['Insurance', 'Insurance.png'], ['Supplies', 'Supplies.png'], ['Personal', 'Personal.png'],
                                ['Education', 'Education.png'], ['Entertainment', 'Entertainment.png'], ['Business', 'Business.png'],
                                ['Repairs', 'Repairs.png'], ['Sport', 'Sport.png']
                                ], required: true %>
        <span class="note">Select an icon</span>
      </div>
      <div class="field">
        <%= form.text_field :name, placeholder: ' Category name', required: true, class: 'input-field' %>
      </div>
      <div class="text-center">
        <%= form.submit class: 'btn-submit btn-cat-new' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container-full">
  <div class="header-block">
    <%= link_to ('<i class="fa-solid fa-arrow-left"></i>').html_safe, root_path, { 'class': 'arrow'} %>
    <span class='title'>Spendings</span>
    <i class="fa-solid fa-magnifying-glass"></i>
  </div>
</div>
<%= render 'total' %>
<div class='cat-total'>
  <%= image_tag("#{@category.icon}") %>
  <span class="cat-name-total"><%= @category.name %> category total: $<%= @total %>0</span>
</div>
<div class="categories-list">
  <ul class="list-group">
    <% @spendings.reverse().each do |spending| %>
      <% if (spending.category_id == @category.id) then %>
        <li class="spend-card">
          <div class="spend-details">
            <div class="name-amount">
              <span><%= spending.name %>:</span>
              <span class="amount">$<%= spending.amount %>0</span>
            </div>
            <span class="date"><%= spending.created_at.to_s.slice(0,10) %></span>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="cat-div">
  <div class="actions-inner">
    <%= link_to 'ADD NEW SPENDING', "/users/#{current_user.id}/categories/#{@category.id}/spendings/new/", class: 'cat-new-btn' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget tracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/e43d7d8b67.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/spendings/new.html.erb
<div class="container-full">
  <div class="header-block">
    <%= link_to ('<i class="fa-solid fa-arrow-left"></i>').html_safe, root_path, { 'class': 'arrow'} %>
    <span class="main-title">Add new spending</span>
    <i class="fa-solid fa-magnifying-glass"></i>
  </div>
  <div class="categories-list">
    <%= form_with model: @spending, url: "/users/#{current_user.id}/categories/#{params[:category_id]}/spendings", method: :post do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="field">
        <%= form.text_field :name, placeholder: 'Spending name', required: true, class: 'input-field' %>
      </div>
      <div class="field">
        <%= form.number_field :amount, placeholder: 'Spending amount', required: true, class: 'input-field' %>
      </div>
      <div class="field select">
        <%= form.select :category_id, @categories.map { |category| [category.name, category.id] }, required: true %>
        <span class="note">Select a category</span>
      </div>
      <div class="text-center">
        <%= form.submit class:"btn-submit btn-cat-new" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-splash">
  <h1 class="header">Budget Tracker</h1>
  <div class="splash">
    <%= image_tag "splash.gif", { class: 'logo' } %>
  </div>
  <% if current_user.nil? %>
    <div class="links">
      <%= link_to 'LOG IN', new_user_session_path, { class: 'btn-login'} %>
      <%= link_to 'SIGN UP', new_user_registration_path, { class: 'sign-up'} %>
    </div>
  <% else %>
    <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: 'sign-in-btn' %>
  <% end %>
</div>